### ISSUE TITLE
error with gtts when running  googlehomepush.

### ISSUE THREAD

**Issue by peterd550** [deblockt/google-home-push#11]
I have been runnig the same script for 6 months
When I run the script I am getting
looks like gtts and gtts-token have changed the api 

WARNING:googlehomepush.googletts:Unable to get language list: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "./ChecksAlert.py", line 14, in <module>
    GoogleHome(host='10.0.0.1').say(text, lang='en-GB') #the google nest
  File "/usr/local/lib/python3.7/dist-packages/googlehomepush/__init__.py", line 35, in say
    ttsurl = self.ttsbuilder(text, lang)
  File "/usr/local/lib/python3.7/dist-packages/googlehomepush/googletts.py", line 141, in googleTTS_builder
    return GoogleTTS(text=text, lang=lang, slow=False).url()
  File "/usr/local/lib/python3.7/dist-packages/googlehomepush/googletts.py", line 87, in url
    part_tk = self.token.calculate_token(self.text)
  File "/usr/local/lib/python3.7/dist-packages/gtts_token/gtts_token.py", line 28, in calculate_token
    seed = self._get_token_key()
  File "/usr/local/lib/python3.7/dist-packages/gtts_token/gtts_token.py", line 59, in _get_token_key
    "Unable to find token seed! Did https://translate.google.com change?"
ValueError: Unable to find token seed! Did https://translate.google.com change?

**Comment by rickstijnman** [comment]
I have the same issue.

**Comment by peterd550** [comment]
Use this 

https://github.com/dray-cyber/googlecontroller

**Comment by rickstijnman** [comment]
thanks :)

**Comment by dray-cyber** [comment]
> Use this 
> 
> https://github.com/dray-cyber/googlecontroller
> 

Ty for the reference.
